Free model, better support for fields

diff --git a/relationality-lab/setup b/relationality-lab/setup
--- a/relationality-lab/setup
+++ b/relationality-lab/setup
@@ -2,7 +2,7 @@
 
 declare -g venv python tooling_reqs
 venv="./tooling-venv"
-python="python3.7"
+python=${PYTHON:-"python3.7"}
 tooling_reqs="./tooling-requirements.txt"
 
 log() { echo "$1" >&2 ; }
@@ -13,6 +13,11 @@ if [[ -d "$venv" ]]; then
   log "Found virtual environment."
 else
   log "Creating virtual environment."
+  if command -v "$python"; then
+    log "Error: python interpreter not found at [$python]"
+    log "Set PYTHON to location of python"
+    exit 1
+  fi
   "$python" -m venv "$venv"
 fi
 
